### ISSUE TITLE
Versão de impressão do perfil de um país

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/country-profile#20]
Verificar se é possível usar o mesmo template aplicando classes do bootstrap para a versão de impressão ou implementar em template separado.

**Comment by viniciusandrade** [comment]
@marcioalvessilva favor considerar a tabela disponível no ambiente de produção para realizar os testes:
https://country-profile.bvsalud.org/profile/COL/

Obrigado

**Comment by marcioalvessilva** [comment]
Mockup atualizado no GitHub

Basicamente precisa inserir bloco de código css (abaixo) e em alguns lugares a classe d-print-none
(breadcrumb, lang e na coluna de menu)

em caso de dúvida pode me chamar

Inserir esse css no final do arquivos css/style.css
@media print {
	#header, #footer{
		padding: 10px;
	}
	#header-title{
		font-size: 18px;
	}
	#logo-opas img{
		max-height: 80px!important;
	}
	.accordion-button{
		background: #fff!important;
		color: #000!important;
	}
	.accordion-button:not(.collapsed)::after{
		display: none;
	}
	#main_container{
		padding: 10px;
	}
	#footer{
		display: nonex;
	}
}

**Comment by viniciusandrade** [comment]
@marcioalvessilva ajustes aplicados no projeto, muito obrigado pelo apoio :+1:
