### ISSUE TITLE
Adicionar o Código do Google Analytics 4

### ISSUE THREAD

**Issue by marcoslmori** [bireme/country-profile#26]
Adicionar a linha do GA-4 G-PY2MR0TWMZ relacionado ao GAU (UA-39600115-50)

**Comment by viniciusandrade** [comment]
@marcoslmori revisei o código mas aparentemente já esta configurado usando o código GA4 conforme view source do site.

Favor confirmar.

**Comment by marcoslmori** [comment]
Validado tanto para o GAU como o GA-4

**Comment by viniciusandrade** [comment]
OK. Obrigado.
